### ISSUE TITLE
ocs-operator updates its status incorrectly

### ISSUE THREAD

**Issue by kshlm** [openshift/ocs-operator#86] opened 2019-09-04 07:59 UTC
The ocs-operator updates its status to not ready when a StorageCluster object is created.

```console
$ oc describe pods ocs-operator-56cffb8fc4-mlhkt                                                                                                                                                                    ✘ 130 
Name:               ocs-operator-56cffb8fc4-mlhkt
Namespace:          openshift-storage
Priority:           0
PriorityClassName:  <none>
Node:               ip-10-0-179-129.us-west-2.compute.internal/10.0.179.129
Start Time:         Wed, 04 Sep 2019 12:25:54 +0530
Labels:             name=ocs-operator
                    pod-template-hash=56cffb8fc4
Annotations:        alm-examples:
                      
                      [
                          {
                              "apiVersion": "ocs.openshift.io/v1alpha1",
                              "kind": "StorageCluster",
                              "metadata": {
                                  "name": "example-storagecluster",
                                  "namespace": "openshift-storage"
                              },
                              "spec": {
                                  "manageNodes": false,
                                  "monPVCTemplate": {
                                      "spec": {
                                          "accessModes": [
                                              "ReadWriteOnce"
                                          ],
                                          "resources": {
                                              "requests": {
                                                  "storage": "10Gi"
                                              }
                                          },
                                          "storageClassName": "gp2"
                                      }
                                  },
                                  "storageDeviceSets": [
                                      {
                                          "count": 3,
                                          "dataPVCTemplate": {
                                              "spec": {
                                                  "accessModes": [
                                                      "ReadWriteOnce"
                                                  ],
                                                  "resources": {
                                                      "requests": {
                                                          "storage": "1Ti"
                                                      }
                                                  },
                                                  "storageClassName": "gp2",
                                                  "volumeMode": "Block"
                                              }
                                          },
                                          "name": "example-deviceset",
                                          "placement": {},
                                          "portable": true,
                                          "resources": {}
                                      }
                                  ]
                              }
                          },
                          {
                              "apiVersion": "ocs.openshift.io/v1alpha1",
                              "kind": "OCSInitialization",
                              "metadata": {
                                  "name": "example-ocsinitialization"
                              },
                              "spec": {}
                          },
                          {
                              "apiVersion": "ocs.openshift.io/v1alpha1",
                              "kind": "StorageClusterInitialization",
                              "metadata": {
                                  "name": "example-storageclusterinitialization"
                              },
                              "spec": {}
                          }
                      ]
                    capabilities: Full Lifecycle
                    categories: Storage
                    olm.operatorGroup: openshift-storage-operatorgroup
                    olm.operatorNamespace: openshift-storage
                    olm.targetNamespaces: openshift-storage
                    openshift.io/scc: restricted
Status:             Running
IP:                 10.130.2.9
Controlled By:      ReplicaSet/ocs-operator-56cffb8fc4
Containers:
  ocs-operator:
    Container ID:  cri-o://d6e7d968eb613f1965bd69de864df10321cc09d9d60aa0a8a128ae8c53fa17eb
    Image:         quay.io/kshlm/ocs-operator:201909041217
    Image ID:      quay.io/kshlm/ocs-operator@sha256:2efcf6d5a77640c65e5dd097b2d1515b22e49b838850d6a3dbc120a4c584552d
    Port:          60000/TCP
    Host Port:     0/TCP
    Command:
      ocs-operator
    State:          Running
      Started:      Wed, 04 Sep 2019 12:26:38 +0530
    Ready:          False
    Restart Count:  0
    Readiness:      exec [stat /tmp/operator-sdk-ready] delay=4s timeout=1s period=10s #success=1 #failure=1
    Environment:
      WATCH_NAMESPACE:   (v1:metadata.annotations['olm.targetNamespaces'])
      POD_NAME:         ocs-operator-56cffb8fc4-mlhkt (v1:metadata.name)
      OPERATOR_NAME:    ocs-operator
      CEPH_IMAGE:       ceph/ceph:v14.2.2-20190828
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ocs-operator-token-bvb6g (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  ocs-operator-token-bvb6g:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ocs-operator-token-bvb6g
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                                                 Message
  ----     ------     ----                   ----                                                 -------
  Normal   Scheduled  63m                    default-scheduler                                    Successfully assigned openshift-storage/ocs-operator-56cffb8fc4-mlhkt to ip-10-0-179-129.us-west-2.compute.internal
  Normal   Pulling    63m                    kubelet, ip-10-0-179-129.us-west-2.compute.internal  Pulling image "quay.io/kshlm/ocs-operator:201909041217"
  Normal   Pulled     63m                    kubelet, ip-10-0-179-129.us-west-2.compute.internal  Successfully pulled image "quay.io/kshlm/ocs-operator:201909041217"
  Normal   Created    63m                    kubelet, ip-10-0-179-129.us-west-2.compute.internal  Created container ocs-operator
  Normal   Started    63m                    kubelet, ip-10-0-179-129.us-west-2.compute.internal  Started container ocs-operator
  Warning  Unhealthy  3m42s (x351 over 62m)  kubelet, ip-10-0-179-129.us-west-2.compute.internal  Readiness probe failed: stat: cannot stat '/tmp/operator-sdk-ready': No such file or directory
```

The operator is still fully functional and can respond to updates to the CRDs it watches.
Only the status of the StorageCluster should be updated, which should depend on the status of the rook resources it creates.

**Comment by kshlm** [comment] 2019-09-04 08:08
I see that this update happens in the StorageCluster controller [here](https://github.com/openshift/ocs-operator/blob/master/pkg/controller/storagecluster/reconcile.go#L123-L131). I don't understand the reason given about being updateable.
If this status is required for the operator itself, maybe we should be doing it someplace else other than the storagecluster controller.
If this status is meant for the StorageCluster resource, then we should be updating the resource and not the operator.

@sacharya can you help here and/or take this up?

**Comment by sacharya** [comment] 2019-09-04 15:11
/cc @mhrivnak @djzager 

The ocs-operator, while already running, is READY when all of the component operator resources are reporting healthy status. It's market READY on startup and is not READY in case of any negative or progressing conditions from component operator resources. This is to prevent OLM from upgrading the ocs-operator while the resources are still progressing or have failed.

Since ocs-operator is marked as not READY, can you get the status of your storageclusters and cephclusters objects?

**Comment by djzager** [comment] 2019-09-04 15:42
> This is to prevent OLM from upgrading the ocs-operator while the resources are still progressing or have failed.

That is the idea here. The thought process is this, if any of the component operators is doing work we want to prevent OLM from interrupting that work (specifically an upgrade because a new CSV has become available). There is no other method currently available to provide this protection to component operators and we want to shield those operators from having to understand OLM internals. I welcome alternatives that 1) prevent component operators from having to understand how OLM install operator updates work 2) prevent OLM from updating an operator that is doing work.

**Comment by mhrivnak** [comment] 2019-09-16 14:19
@kshlm WDYT?

It comes down to: it's working as designed, the design is mostly a product of OLM's expectations, we don't love the design, but it's the best we can do until OLM provides a better mechanism. We can discuss further if that would be helpful.

**Comment by kshlm** [comment] 2019-09-16 14:46
Thanks for the explanations @sacharya @djzager @mhrivnak. I get the reasoning for the design now, and understand that this is the best we have at the moment. Hopefully, we have a better solution to this soon.

The changing status of the ocs-operator has been a little problematic for testing scripts, which get confused by the status moving back to installing after a successful installation. We'll need to add documentation to explain this better.

**Comment by kshlm** [comment] 2019-09-16 16:39
Just found this https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-gate which could be useful. Instead of changing the container readiness, we could add unique readiness gate for ocs-operator being in operation.

**Comment by djzager** [comment] 2019-09-18 13:09
@kshlm that is an interesting find. My immediate reaction is that we would have to be patching ocs-operator pods directly instead of simply updating the status on the resource we own. I would happily consider the argument that this is a better approach than status/conditions + readiness probe on the deployment. Perhaps you could construct one?

**Comment by dmesser** [comment] 2020-01-17 10:56
@dzjager @kshlm @mhrivnak  good discussion here. I think we reached a point where we (OLM) need to re-evaluate the way we signal readiness to update from Operator back to OLM. The readiness gates seems like a welcome evolution and may just do the job.

**Comment by kubealex** [comment] 2020-08-24 08:48
news?

**Closed** 2021-01-21 12:42 UTC
Labels: lifecycle/rotten
